// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PackageType int32

const (
	PackageType_UN_KNOWN          PackageType = 0
	PackageType_SIGN_IN_REQ       PackageType = 1
	PackageType_SIGN_IN_RESP      PackageType = 2
	PackageType_SYNC_REQ          PackageType = 3
	PackageType_SYNC_RESP         PackageType = 4
	PackageType_HEADBEAT_REQ      PackageType = 5
	PackageType_HEADBEAT_RESP     PackageType = 6
	PackageType_SEND_MESSAGE_REQ  PackageType = 7
	PackageType_SEND_MESSAGE_RESP PackageType = 8
	PackageType_MESSAGE           PackageType = 9
	PackageType_MESSAGE_ACK       PackageType = 10
)

var PackageType_name = map[int32]string{
	0:  "UN_KNOWN",
	1:  "SIGN_IN_REQ",
	2:  "SIGN_IN_RESP",
	3:  "SYNC_REQ",
	4:  "SYNC_RESP",
	5:  "HEADBEAT_REQ",
	6:  "HEADBEAT_RESP",
	7:  "SEND_MESSAGE_REQ",
	8:  "SEND_MESSAGE_RESP",
	9:  "MESSAGE",
	10: "MESSAGE_ACK",
}

var PackageType_value = map[string]int32{
	"UN_KNOWN":          0,
	"SIGN_IN_REQ":       1,
	"SIGN_IN_RESP":      2,
	"SYNC_REQ":          3,
	"SYNC_RESP":         4,
	"HEADBEAT_REQ":      5,
	"HEADBEAT_RESP":     6,
	"SEND_MESSAGE_REQ":  7,
	"SEND_MESSAGE_RESP": 8,
	"MESSAGE":           9,
	"MESSAGE_ACK":       10,
}

func (x PackageType) String() string {
	return proto.EnumName(PackageType_name, int32(x))
}

func (PackageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

// 消息类型
type MessageType int32

const (
	MessageType_DEFALUT  MessageType = 0
	MessageType_TEXT     MessageType = 1
	MessageType_FACE     MessageType = 2
	MessageType_VOICE    MessageType = 3
	MessageType_IMAGE    MessageType = 4
	MessageType_FILE     MessageType = 5
	MessageType_LOCATION MessageType = 6
	MessageType_COMMAND  MessageType = 7
	MessageType_CUSTOM   MessageType = 8
)

var MessageType_name = map[int32]string{
	0: "DEFALUT",
	1: "TEXT",
	2: "FACE",
	3: "VOICE",
	4: "IMAGE",
	5: "FILE",
	6: "LOCATION",
	7: "COMMAND",
	8: "CUSTOM",
}

var MessageType_value = map[string]int32{
	"DEFALUT":  0,
	"TEXT":     1,
	"FACE":     2,
	"VOICE":    3,
	"IMAGE":    4,
	"FILE":     5,
	"LOCATION": 6,
	"COMMAND":  7,
	"CUSTOM":   8,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

type ErrCode int32

const (
	ErrCode_SUCCESS        ErrCode = 0
	ErrCode_SERVER_UNKNOWN ErrCode = 1001
)

var ErrCode_name = map[int32]string{
	0:    "SUCCESS",
	1001: "SERVER_UNKNOWN",
}

var ErrCode_value = map[string]int32{
	"SUCCESS":        0,
	"SERVER_UNKNOWN": 1001,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

type ReceiverType int32

const (
	ReceiverType_UNKNOWN ReceiverType = 0
	ReceiverType_USER    ReceiverType = 1
	ReceiverType_GROUP   ReceiverType = 2
)

var ReceiverType_name = map[int32]string{
	0: "UNKNOWN",
	1: "USER",
	2: "GROUP",
}

var ReceiverType_value = map[string]int32{
	"UNKNOWN": 0,
	"USER":    1,
	"GROUP":   2,
}

func (x ReceiverType) String() string {
	return proto.EnumName(ReceiverType_name, int32(x))
}

func (ReceiverType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

// 消息体
type MessageBody struct {
	MessageType          MessageType     `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=pb.MessageType" json:"message_type,omitempty"`
	MessageContent       *MessageContent `protobuf:"bytes,2,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MessageBody) Reset()         { *m = MessageBody{} }
func (m *MessageBody) String() string { return proto.CompactTextString(m) }
func (*MessageBody) ProtoMessage()    {}
func (*MessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *MessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBody.Unmarshal(m, b)
}
func (m *MessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBody.Marshal(b, m, deterministic)
}
func (m *MessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBody.Merge(m, src)
}
func (m *MessageBody) XXX_Size() int {
	return xxx_messageInfo_MessageBody.Size(m)
}
func (m *MessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBody proto.InternalMessageInfo

func (m *MessageBody) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_DEFALUT
}

func (m *MessageBody) GetMessageContent() *MessageContent {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

// 消息内容，MessageType：1
type MessageContent struct {
	// Types that are valid to be assigned to Content:
	//	*MessageContent_Text
	//	*MessageContent_Face
	//	*MessageContent_Voice
	//	*MessageContent_Image
	//	*MessageContent_File
	//	*MessageContent_Location
	//	*MessageContent_Command
	//	*MessageContent_Custom
	Content              isMessageContent_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MessageContent) Reset()         { *m = MessageContent{} }
func (m *MessageContent) String() string { return proto.CompactTextString(m) }
func (*MessageContent) ProtoMessage()    {}
func (*MessageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *MessageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageContent.Unmarshal(m, b)
}
func (m *MessageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageContent.Marshal(b, m, deterministic)
}
func (m *MessageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageContent.Merge(m, src)
}
func (m *MessageContent) XXX_Size() int {
	return xxx_messageInfo_MessageContent.Size(m)
}
func (m *MessageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageContent.DiscardUnknown(m)
}

var xxx_messageInfo_MessageContent proto.InternalMessageInfo

type isMessageContent_Content interface {
	isMessageContent_Content()
}

type MessageContent_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MessageContent_Face struct {
	Face *Face `protobuf:"bytes,2,opt,name=face,proto3,oneof"`
}

type MessageContent_Voice struct {
	Voice *Voice `protobuf:"bytes,3,opt,name=voice,proto3,oneof"`
}

type MessageContent_Image struct {
	Image *Image `protobuf:"bytes,4,opt,name=image,proto3,oneof"`
}

type MessageContent_File struct {
	File *File `protobuf:"bytes,5,opt,name=file,proto3,oneof"`
}

type MessageContent_Location struct {
	Location *Location `protobuf:"bytes,6,opt,name=location,proto3,oneof"`
}

type MessageContent_Command struct {
	Command *Command `protobuf:"bytes,7,opt,name=command,proto3,oneof"`
}

type MessageContent_Custom struct {
	Custom *Custom `protobuf:"bytes,8,opt,name=custom,proto3,oneof"`
}

func (*MessageContent_Text) isMessageContent_Content() {}

func (*MessageContent_Face) isMessageContent_Content() {}

func (*MessageContent_Voice) isMessageContent_Content() {}

func (*MessageContent_Image) isMessageContent_Content() {}

func (*MessageContent_File) isMessageContent_Content() {}

func (*MessageContent_Location) isMessageContent_Content() {}

func (*MessageContent_Command) isMessageContent_Content() {}

func (*MessageContent_Custom) isMessageContent_Content() {}

func (m *MessageContent) GetContent() isMessageContent_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MessageContent) GetText() *Text {
	if x, ok := m.GetContent().(*MessageContent_Text); ok {
		return x.Text
	}
	return nil
}

func (m *MessageContent) GetFace() *Face {
	if x, ok := m.GetContent().(*MessageContent_Face); ok {
		return x.Face
	}
	return nil
}

func (m *MessageContent) GetVoice() *Voice {
	if x, ok := m.GetContent().(*MessageContent_Voice); ok {
		return x.Voice
	}
	return nil
}

func (m *MessageContent) GetImage() *Image {
	if x, ok := m.GetContent().(*MessageContent_Image); ok {
		return x.Image
	}
	return nil
}

func (m *MessageContent) GetFile() *File {
	if x, ok := m.GetContent().(*MessageContent_File); ok {
		return x.File
	}
	return nil
}

func (m *MessageContent) GetLocation() *Location {
	if x, ok := m.GetContent().(*MessageContent_Location); ok {
		return x.Location
	}
	return nil
}

func (m *MessageContent) GetCommand() *Command {
	if x, ok := m.GetContent().(*MessageContent_Command); ok {
		return x.Command
	}
	return nil
}

func (m *MessageContent) GetCustom() *Custom {
	if x, ok := m.GetContent().(*MessageContent_Custom); ok {
		return x.Custom
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageContent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageContent_Text)(nil),
		(*MessageContent_Face)(nil),
		(*MessageContent_Voice)(nil),
		(*MessageContent_Image)(nil),
		(*MessageContent_File)(nil),
		(*MessageContent_Location)(nil),
		(*MessageContent_Command)(nil),
		(*MessageContent_Custom)(nil),
	}
}

// 文本消息
type Text struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// 表情消息
type Face struct {
	FaceId               int64    `protobuf:"varint,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	FaceUrl              string   `protobuf:"bytes,2,opt,name=face_url,json=faceUrl,proto3" json:"face_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Face) Reset()         { *m = Face{} }
func (m *Face) String() string { return proto.CompactTextString(m) }
func (*Face) ProtoMessage()    {}
func (*Face) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *Face) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Face.Unmarshal(m, b)
}
func (m *Face) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Face.Marshal(b, m, deterministic)
}
func (m *Face) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Face.Merge(m, src)
}
func (m *Face) XXX_Size() int {
	return xxx_messageInfo_Face.Size(m)
}
func (m *Face) XXX_DiscardUnknown() {
	xxx_messageInfo_Face.DiscardUnknown(m)
}

var xxx_messageInfo_Face proto.InternalMessageInfo

func (m *Face) GetFaceId() int64 {
	if m != nil {
		return m.FaceId
	}
	return 0
}

func (m *Face) GetFaceUrl() string {
	if m != nil {
		return m.FaceUrl
	}
	return ""
}

// 语音消息
type Voice struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Duration             int32    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voice) Reset()         { *m = Voice{} }
func (m *Voice) String() string { return proto.CompactTextString(m) }
func (*Voice) ProtoMessage()    {}
func (*Voice) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *Voice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voice.Unmarshal(m, b)
}
func (m *Voice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voice.Marshal(b, m, deterministic)
}
func (m *Voice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voice.Merge(m, src)
}
func (m *Voice) XXX_Size() int {
	return xxx_messageInfo_Voice.Size(m)
}
func (m *Voice) XXX_DiscardUnknown() {
	xxx_messageInfo_Voice.DiscardUnknown(m)
}

var xxx_messageInfo_Voice proto.InternalMessageInfo

func (m *Voice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Voice) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Voice) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Voice) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 图片消息
type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

// 文件消息
type File struct {
	Id                   int64    `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,14,opt,name=size,proto3" json:"size,omitempty"`
	Url                  string   `protobuf:"bytes,15,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 地理位置消息
type Location struct {
	Desc                 string   `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{7}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

// Command 指令推送，1000以下，IM内部用，1000以上，留给业务用
type Command struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{8}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Command) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 自定义消息
type Custom struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Custom) Reset()         { *m = Custom{} }
func (m *Custom) String() string { return proto.CompactTextString(m) }
func (*Custom) ProtoMessage()    {}
func (*Custom) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{9}
}

func (m *Custom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Custom.Unmarshal(m, b)
}
func (m *Custom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Custom.Marshal(b, m, deterministic)
}
func (m *Custom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Custom.Merge(m, src)
}
func (m *Custom) XXX_Size() int {
	return xxx_messageInfo_Custom.Size(m)
}
func (m *Custom) XXX_DiscardUnknown() {
	xxx_messageInfo_Custom.DiscardUnknown(m)
}

var xxx_messageInfo_Custom proto.InternalMessageInfo

func (m *Custom) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 设备登录
type SignInReq struct {
	AppId                int64    `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInReq) Reset()         { *m = SignInReq{} }
func (m *SignInReq) String() string { return proto.CompactTextString(m) }
func (*SignInReq) ProtoMessage()    {}
func (*SignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{10}
}

func (m *SignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq.Unmarshal(m, b)
}
func (m *SignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq.Marshal(b, m, deterministic)
}
func (m *SignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq.Merge(m, src)
}
func (m *SignInReq) XXX_Size() int {
	return xxx_messageInfo_SignInReq.Size(m)
}
func (m *SignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq proto.InternalMessageInfo

func (m *SignInReq) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *SignInReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *SignInReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SignInReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 设备登录回执
type SignInResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResp) Reset()         { *m = SignInResp{} }
func (m *SignInResp) String() string { return proto.CompactTextString(m) }
func (*SignInResp) ProtoMessage()    {}
func (*SignInResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{11}
}

func (m *SignInResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResp.Unmarshal(m, b)
}
func (m *SignInResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResp.Marshal(b, m, deterministic)
}
func (m *SignInResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResp.Merge(m, src)
}
func (m *SignInResp) XXX_Size() int {
	return xxx_messageInfo_SignInResp.Size(m)
}
func (m *SignInResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResp proto.InternalMessageInfo

func (m *SignInResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SignInResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 消息同步请求
type SyncReq struct {
	DeviceAck            int64    `protobuf:"varint,1,opt,name=device_ack,json=deviceAck,proto3" json:"device_ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncReq) Reset()         { *m = SyncReq{} }
func (m *SyncReq) String() string { return proto.CompactTextString(m) }
func (*SyncReq) ProtoMessage()    {}
func (*SyncReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{12}
}

func (m *SyncReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncReq.Unmarshal(m, b)
}
func (m *SyncReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncReq.Marshal(b, m, deterministic)
}
func (m *SyncReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncReq.Merge(m, src)
}
func (m *SyncReq) XXX_Size() int {
	return xxx_messageInfo_SyncReq.Size(m)
}
func (m *SyncReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncReq proto.InternalMessageInfo

func (m *SyncReq) GetDeviceAck() int64 {
	if m != nil {
		return m.DeviceAck
	}
	return 0
}

// 消息同步响应
type SyncResp struct {
	Code                 int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Messages             []*MessageItem `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SyncResp) Reset()         { *m = SyncResp{} }
func (m *SyncResp) String() string { return proto.CompactTextString(m) }
func (*SyncResp) ProtoMessage()    {}
func (*SyncResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{13}
}

func (m *SyncResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResp.Unmarshal(m, b)
}
func (m *SyncResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResp.Marshal(b, m, deterministic)
}
func (m *SyncResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResp.Merge(m, src)
}
func (m *SyncResp) XXX_Size() int {
	return xxx_messageInfo_SyncResp.Size(m)
}
func (m *SyncResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResp proto.InternalMessageInfo

func (m *SyncResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SyncResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SyncResp) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

// 发送消息请求
type SendMessageReq struct {
	ReceiverType         ReceiverType   `protobuf:"varint,1,opt,name=receiver_type,json=receiverType,proto3,enum=pb.ReceiverType" json:"receiver_type,omitempty"`
	ReceiverId           int64          `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ToUserIds            []int64        `protobuf:"varint,3,rep,packed,name=to_user_ids,json=toUserIds,proto3" json:"to_user_ids,omitempty"`
	MessageBody          []*MessageBody `protobuf:"bytes,4,rep,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	MessageId            string         `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SendTime             int64          `protobuf:"varint,6,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{14}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetReceiverType() ReceiverType {
	if m != nil {
		return m.ReceiverType
	}
	return ReceiverType_UNKNOWN
}

func (m *SendMessageReq) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *SendMessageReq) GetToUserIds() []int64 {
	if m != nil {
		return m.ToUserIds
	}
	return nil
}

func (m *SendMessageReq) GetMessageBody() []*MessageBody {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

func (m *SendMessageReq) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SendMessageReq) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

// 发送消息响应
type SendMessageResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId            int64    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResp) Reset()         { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()    {}
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{15}
}

func (m *SendMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResp.Unmarshal(m, b)
}
func (m *SendMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResp.Marshal(b, m, deterministic)
}
func (m *SendMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResp.Merge(m, src)
}
func (m *SendMessageResp) XXX_Size() int {
	return xxx_messageInfo_SendMessageResp.Size(m)
}
func (m *SendMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResp proto.InternalMessageInfo

func (m *SendMessageResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SendMessageResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendMessageResp) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

// 消息投递
type Message struct {
	Message              *MessageItem `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{16}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() *MessageItem {
	if m != nil {
		return m.Message
	}
	return nil
}

// 单条消息投递内容,todo 通知栏提醒
type MessageItem struct {
	MessageId            string       `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderType           int32        `protobuf:"varint,2,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	SenderId             int64        `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderDeviceId       int64        `protobuf:"varint,4,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	SendInfo             *SenderInfo  `protobuf:"bytes,5,opt,name=send_info,json=sendInfo,proto3" json:"send_info,omitempty"`
	ReceiverType         int32        `protobuf:"varint,6,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	ReceiverId           int64        `protobuf:"varint,7,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ToUserIds            []int64      `protobuf:"varint,8,rep,packed,name=to_user_ids,json=toUserIds,proto3" json:"to_user_ids,omitempty"`
	MessageBody          *MessageBody `protobuf:"bytes,9,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	UserSeq              int64        `protobuf:"varint,10,opt,name=user_seq,json=userSeq,proto3" json:"user_seq,omitempty"`
	SendTime             int64        `protobuf:"varint,11,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Status               int32        `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MessageItem) Reset()         { *m = MessageItem{} }
func (m *MessageItem) String() string { return proto.CompactTextString(m) }
func (*MessageItem) ProtoMessage()    {}
func (*MessageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{17}
}

func (m *MessageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageItem.Unmarshal(m, b)
}
func (m *MessageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageItem.Marshal(b, m, deterministic)
}
func (m *MessageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageItem.Merge(m, src)
}
func (m *MessageItem) XXX_Size() int {
	return xxx_messageInfo_MessageItem.Size(m)
}
func (m *MessageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageItem.DiscardUnknown(m)
}

var xxx_messageInfo_MessageItem proto.InternalMessageInfo

func (m *MessageItem) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *MessageItem) GetSenderType() int32 {
	if m != nil {
		return m.SenderType
	}
	return 0
}

func (m *MessageItem) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *MessageItem) GetSenderDeviceId() int64 {
	if m != nil {
		return m.SenderDeviceId
	}
	return 0
}

func (m *MessageItem) GetSendInfo() *SenderInfo {
	if m != nil {
		return m.SendInfo
	}
	return nil
}

func (m *MessageItem) GetReceiverType() int32 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *MessageItem) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *MessageItem) GetToUserIds() []int64 {
	if m != nil {
		return m.ToUserIds
	}
	return nil
}

func (m *MessageItem) GetMessageBody() *MessageBody {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

func (m *MessageItem) GetUserSeq() int64 {
	if m != nil {
		return m.UserSeq
	}
	return 0
}

func (m *MessageItem) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *MessageItem) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 发送者信息
type SenderInfo struct {
	Lable                string   `protobuf:"bytes,1,opt,name=lable,proto3" json:"lable,omitempty"`
	GroupUserExtra       string   `protobuf:"bytes,2,opt,name=group_user_extra,json=groupUserExtra,proto3" json:"group_user_extra,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Sex                  string   `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`
	UserExtra            string   `protobuf:"bytes,6,opt,name=user_extra,json=userExtra,proto3" json:"user_extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SenderInfo) Reset()         { *m = SenderInfo{} }
func (m *SenderInfo) String() string { return proto.CompactTextString(m) }
func (*SenderInfo) ProtoMessage()    {}
func (*SenderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{18}
}

func (m *SenderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderInfo.Unmarshal(m, b)
}
func (m *SenderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderInfo.Marshal(b, m, deterministic)
}
func (m *SenderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderInfo.Merge(m, src)
}
func (m *SenderInfo) XXX_Size() int {
	return xxx_messageInfo_SenderInfo.Size(m)
}
func (m *SenderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SenderInfo proto.InternalMessageInfo

func (m *SenderInfo) GetLable() string {
	if m != nil {
		return m.Lable
	}
	return ""
}

func (m *SenderInfo) GetGroupUserExtra() string {
	if m != nil {
		return m.GroupUserExtra
	}
	return ""
}

func (m *SenderInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *SenderInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *SenderInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *SenderInfo) GetUserExtra() string {
	if m != nil {
		return m.UserExtra
	}
	return ""
}

// 投递消息回执
type MessageACK struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DeviceAck            int64    `protobuf:"varint,2,opt,name=device_ack,json=deviceAck,proto3" json:"device_ack,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,3,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageACK) Reset()         { *m = MessageACK{} }
func (m *MessageACK) String() string { return proto.CompactTextString(m) }
func (*MessageACK) ProtoMessage()    {}
func (*MessageACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{19}
}

func (m *MessageACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageACK.Unmarshal(m, b)
}
func (m *MessageACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageACK.Marshal(b, m, deterministic)
}
func (m *MessageACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageACK.Merge(m, src)
}
func (m *MessageACK) XXX_Size() int {
	return xxx_messageInfo_MessageACK.Size(m)
}
func (m *MessageACK) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageACK.DiscardUnknown(m)
}

var xxx_messageInfo_MessageACK proto.InternalMessageInfo

func (m *MessageACK) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *MessageACK) GetDeviceAck() int64 {
	if m != nil {
		return m.DeviceAck
	}
	return 0
}

func (m *MessageACK) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.PackageType", PackageType_name, PackageType_value)
	proto.RegisterEnum("pb.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("pb.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterEnum("pb.ReceiverType", ReceiverType_name, ReceiverType_value)
	proto.RegisterType((*MessageBody)(nil), "pb.MessageBody")
	proto.RegisterType((*MessageContent)(nil), "pb.MessageContent")
	proto.RegisterType((*Text)(nil), "pb.Text")
	proto.RegisterType((*Face)(nil), "pb.Face")
	proto.RegisterType((*Voice)(nil), "pb.Voice")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*Command)(nil), "pb.Command")
	proto.RegisterType((*Custom)(nil), "pb.Custom")
	proto.RegisterType((*SignInReq)(nil), "pb.SignInReq")
	proto.RegisterType((*SignInResp)(nil), "pb.SignInResp")
	proto.RegisterType((*SyncReq)(nil), "pb.SyncReq")
	proto.RegisterType((*SyncResp)(nil), "pb.SyncResp")
	proto.RegisterType((*SendMessageReq)(nil), "pb.SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "pb.SendMessageResp")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageItem)(nil), "pb.MessageItem")
	proto.RegisterType((*SenderInfo)(nil), "pb.SenderInfo")
	proto.RegisterType((*MessageACK)(nil), "pb.MessageACK")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 1310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x72, 0xdb, 0x54,
	0x10, 0xb6, 0x2d, 0xdb, 0x92, 0x56, 0x8e, 0xa3, 0x1e, 0x5a, 0x70, 0x4b, 0x7f, 0x05, 0x33, 0x84,
	0x74, 0xa6, 0x03, 0x01, 0x6e, 0xca, 0x95, 0xeb, 0xa8, 0x8d, 0xa6, 0x89, 0x6d, 0x24, 0xbb, 0xb4,
	0x37, 0x78, 0x14, 0xe9, 0x34, 0xd1, 0xc4, 0x92, 0x5c, 0x49, 0x0e, 0x09, 0xc3, 0xf0, 0x42, 0xbc,
	0x00, 0x17, 0xbc, 0x01, 0x4f, 0xc2, 0x1b, 0x70, 0xc9, 0xec, 0x9e, 0x23, 0xd9, 0x4e, 0x18, 0x3a,
	0xbd, 0x3b, 0xfb, 0x7d, 0x7b, 0x76, 0xcf, 0x7e, 0xbb, 0x5a, 0x1b, 0xba, 0x8b, 0x2c, 0x2d, 0xd2,
	0x20, 0x9d, 0x3f, 0xa1, 0x03, 0x6b, 0x2c, 0x8e, 0xad, 0xdf, 0xc0, 0x38, 0xe2, 0x79, 0xee, 0x9f,
	0xf0, 0x67, 0x69, 0x78, 0xc9, 0xf6, 0xa0, 0x13, 0x0b, 0x73, 0x56, 0x5c, 0x2e, 0x78, 0xaf, 0xfe,
	0xb0, 0xbe, 0xd3, 0xdd, 0xdb, 0x7e, 0xb2, 0x38, 0x7e, 0x22, 0xdd, 0x26, 0x97, 0x0b, 0xee, 0x1a,
	0xf1, 0xca, 0x60, 0xdf, 0xc3, 0x76, 0x79, 0x27, 0x48, 0x93, 0x82, 0x27, 0x45, 0xaf, 0xf1, 0xb0,
	0xbe, 0x63, 0xec, 0xb1, 0xb5, 0x6b, 0x03, 0xc1, 0xb8, 0xdd, 0x78, 0xc3, 0xb6, 0xfe, 0x6c, 0x40,
	0x77, 0xd3, 0x85, 0xdd, 0x87, 0x66, 0xc1, 0x2f, 0x0a, 0xca, 0x6d, 0xec, 0x69, 0x18, 0x64, 0xc2,
	0x2f, 0x8a, 0x83, 0x9a, 0x4b, 0x38, 0xf2, 0x6f, 0xfd, 0x80, 0xcb, 0x24, 0xc4, 0x3f, 0xf7, 0x03,
	0x8e, 0x3c, 0xe2, 0xec, 0x11, 0xb4, 0xce, 0xd3, 0x28, 0xe0, 0x3d, 0x85, 0x1c, 0x74, 0x74, 0x78,
	0x85, 0xc0, 0x41, 0xcd, 0x15, 0x0c, 0xba, 0x44, 0xb1, 0x7f, 0xc2, 0x7b, 0xcd, 0x95, 0x8b, 0x83,
	0x00, 0xba, 0x10, 0x43, 0x59, 0xa2, 0x39, 0xef, 0xb5, 0xd6, 0xb2, 0x44, 0x73, 0x91, 0x25, 0x9a,
	0x73, 0xb6, 0x0b, 0xda, 0x3c, 0x0d, 0xfc, 0x22, 0x4a, 0x93, 0x5e, 0x9b, 0x7c, 0x3a, 0xe8, 0x73,
	0x28, 0xb1, 0x83, 0x9a, 0x5b, 0xf1, 0xec, 0x0b, 0x50, 0x83, 0x34, 0x8e, 0xfd, 0x24, 0xec, 0xa9,
	0xe4, 0x6a, 0xa0, 0xeb, 0x40, 0x40, 0x07, 0x35, 0xb7, 0x64, 0xd9, 0xe7, 0xd0, 0x0e, 0x96, 0x79,
	0x91, 0xc6, 0x3d, 0x8d, 0xfc, 0x80, 0xfc, 0x08, 0x39, 0xa8, 0xb9, 0x92, 0x7b, 0xa6, 0x63, 0x38,
	0x21, 0xdf, 0x1d, 0x68, 0xa2, 0x36, 0x8c, 0xad, 0x69, 0xa6, 0x0b, 0x9d, 0xac, 0xa7, 0xd0, 0x44,
	0x5d, 0xd8, 0x27, 0xa0, 0xa2, 0x2e, 0xb3, 0x28, 0x24, 0x5a, 0x71, 0xdb, 0x68, 0x3a, 0x21, 0xbb,
	0x0d, 0x1a, 0x11, 0xcb, 0x6c, 0x4e, 0x62, 0xea, 0x2e, 0x39, 0x4e, 0xb3, 0xb9, 0xf5, 0x06, 0x5a,
	0x24, 0x19, 0xeb, 0x42, 0x43, 0xde, 0xd3, 0xdd, 0x46, 0x14, 0x62, 0xa2, 0x3c, 0xfa, 0x45, 0x88,
	0xdf, 0x72, 0xe9, 0xcc, 0xee, 0x80, 0x16, 0x2e, 0x33, 0x21, 0x85, 0x42, 0x78, 0x65, 0x33, 0x13,
	0x14, 0x0c, 0xdf, 0xa4, 0x00, 0x78, 0xb4, 0x7e, 0x85, 0x16, 0x49, 0x7d, 0x2d, 0xf4, 0x4d, 0x68,
	0xfd, 0x1c, 0x85, 0xc5, 0xa9, 0x8c, 0x2d, 0x0c, 0xf6, 0x31, 0xb4, 0x4f, 0x79, 0x74, 0x72, 0x5a,
	0xc8, 0xd0, 0xd2, 0xba, 0x1e, 0x98, 0x7d, 0x06, 0x5b, 0xc5, 0xe9, 0x32, 0x3e, 0x4e, 0xfc, 0x68,
	0x4e, 0x35, 0xb5, 0x88, 0xeb, 0x54, 0x20, 0x16, 0x36, 0x86, 0x26, 0xb6, 0x51, 0x26, 0xef, 0x90,
	0x1e, 0xb2, 0xae, 0xc4, 0x8f, 0x79, 0x6f, 0x4b, 0x08, 0x88, 0xe7, 0xaa, 0xd6, 0x2e, 0x79, 0x89,
	0x5a, 0x65, 0xda, 0xed, 0x55, 0x3d, 0xaf, 0x41, 0x2b, 0x9b, 0x8e, 0x37, 0x42, 0x9e, 0x07, 0x65,
	0x1b, 0xf0, 0x8c, 0xea, 0xcc, 0xfd, 0x22, 0x2a, 0x96, 0xa1, 0x50, 0xad, 0xee, 0x56, 0x36, 0xbb,
	0x0b, 0xfa, 0x3c, 0x4d, 0x4e, 0x04, 0xa9, 0x10, 0xb9, 0x02, 0xac, 0xaf, 0x41, 0x95, 0x33, 0x82,
	0x81, 0x83, 0x34, 0x14, 0xdf, 0x63, 0xcb, 0xa5, 0x33, 0x25, 0xf3, 0x0b, 0x9f, 0x82, 0x76, 0x5c,
	0x3a, 0x5b, 0x77, 0xa1, 0x2d, 0xc6, 0xa5, 0x62, 0xcb, 0xa7, 0x20, 0x9b, 0x80, 0xee, 0x45, 0x27,
	0x89, 0x93, 0xb8, 0xfc, 0x1d, 0xbb, 0x05, 0x6d, 0x7f, 0xb1, 0x58, 0x4d, 0x45, 0xcb, 0x5f, 0x2c,
	0x9c, 0x90, 0x7d, 0x0a, 0x7a, 0xc8, 0xcf, 0x23, 0x31, 0x2f, 0x0d, 0x62, 0x34, 0x01, 0x38, 0x21,
	0x8e, 0xd2, 0x32, 0xe7, 0x19, 0x52, 0x8a, 0x18, 0x25, 0x34, 0x1d, 0xea, 0x5d, 0x91, 0x9e, 0xf1,
	0x44, 0xf6, 0x43, 0x18, 0xd6, 0x53, 0x80, 0x32, 0x5f, 0xbe, 0xf8, 0xcf, 0x1a, 0x7a, 0xa0, 0xca,
	0x85, 0x50, 0x4e, 0xa0, 0x34, 0xad, 0x1d, 0x50, 0xbd, 0xcb, 0x24, 0xc0, 0x97, 0xde, 0x03, 0x90,
	0x4f, 0xf2, 0x83, 0x33, 0xf9, 0x5a, 0xf9, 0xc8, 0x7e, 0x70, 0x66, 0x71, 0xd0, 0x84, 0xe7, 0x87,
	0xe6, 0x60, 0x8f, 0x41, 0x93, 0xc7, 0xbc, 0xa7, 0x3c, 0x54, 0x76, 0x8c, 0x8d, 0x4d, 0xe7, 0x14,
	0x3c, 0x76, 0x2b, 0x07, 0xeb, 0x9f, 0x3a, 0x74, 0x3d, 0x9e, 0x84, 0x92, 0xc5, 0x87, 0x7d, 0x07,
	0x5b, 0x19, 0x0f, 0x78, 0x74, 0xce, 0xb3, 0xf5, 0x75, 0x69, 0x62, 0x10, 0x57, 0x12, 0xb4, 0x2f,
	0x3b, 0xd9, 0x9a, 0xc5, 0x1e, 0x80, 0x51, 0x5d, 0xab, 0x44, 0x86, 0x12, 0x72, 0x42, 0x76, 0x1f,
	0x8c, 0x22, 0x9d, 0x49, 0xa5, 0xc5, 0xd3, 0x14, 0x57, 0x2f, 0xd2, 0x29, 0x89, 0x9d, 0xaf, 0x6f,
	0xe9, 0xe3, 0x34, 0xbc, 0xec, 0x35, 0xaf, 0xbd, 0x1d, 0x97, 0x79, 0xb5, 0xa5, 0x69, 0xb3, 0xdf,
	0x03, 0x28, 0xef, 0x44, 0xa1, 0xfc, 0x34, 0x74, 0x89, 0x88, 0xb6, 0xe7, 0x3c, 0x09, 0x67, 0x45,
	0x14, 0x73, 0xda, 0x67, 0x8a, 0xab, 0x21, 0x30, 0x89, 0x62, 0x6e, 0xfd, 0x04, 0xdb, 0x1b, 0x95,
	0x7f, 0xb0, 0xd0, 0x9b, 0xc9, 0xc5, 0xe8, 0xac, 0x92, 0x5b, 0xdf, 0x82, 0x2a, 0x63, 0xb3, 0x2f,
	0x57, 0x31, 0xc4, 0xfe, 0xbf, 0xd6, 0x91, 0x6a, 0x42, 0x7e, 0x57, 0xaa, 0xdf, 0x2e, 0x24, 0xae,
	0x24, 0xa9, 0x5f, 0xad, 0xf0, 0x01, 0x18, 0x58, 0x50, 0xd9, 0x2a, 0xb1, 0x64, 0x40, 0x40, 0xd4,
	0x16, 0x29, 0xc1, 0xfa, 0x78, 0x6b, 0x02, 0x70, 0x42, 0xb6, 0x03, 0xa6, 0x24, 0x57, 0x5f, 0x47,
	0x93, 0x7c, 0xba, 0x02, 0xdf, 0x2f, 0xbf, 0x91, 0xc7, 0x52, 0xc9, 0x28, 0x79, 0x9b, 0xca, 0x5f,
	0x8f, 0x2e, 0xd6, 0xe0, 0x89, 0x50, 0xc9, 0xdb, 0x54, 0x84, 0xc5, 0x13, 0xee, 0xac, 0xcd, 0x09,
	0x6a, 0xd3, 0xb3, 0xfe, 0x77, 0x5e, 0xd4, 0xf7, 0xcd, 0x8b, 0xf6, 0xbe, 0x79, 0xd1, 0xaf, 0x29,
	0x7b, 0x7d, 0x5e, 0x6e, 0x83, 0x46, 0x01, 0x73, 0xfe, 0xae, 0x07, 0x94, 0x91, 0x3e, 0x7d, 0x8f,
	0xbf, 0xdb, 0x9c, 0x15, 0x63, 0x73, 0x56, 0x70, 0x5f, 0xe7, 0x85, 0x5f, 0x2c, 0x73, 0x5a, 0xae,
	0x2d, 0x57, 0x5a, 0xd6, 0x1f, 0x75, 0x80, 0x95, 0x04, 0xb8, 0x30, 0xe6, 0xfe, 0xf1, 0x9c, 0xcb,
	0x3e, 0x09, 0x03, 0x55, 0x3e, 0xc9, 0xd2, 0xe5, 0x42, 0xd4, 0xc2, 0x2f, 0x8a, 0xcc, 0x97, 0xa3,
	0xd4, 0x25, 0x1c, 0x0b, 0xb2, 0x11, 0xc5, 0xad, 0x9a, 0x44, 0xc1, 0x19, 0xed, 0x6c, 0x85, 0x3c,
	0x2a, 0x1b, 0x07, 0xc1, 0x3f, 0xf7, 0x0b, 0x3f, 0x9b, 0xad, 0x7e, 0x21, 0x74, 0x81, 0x4c, 0xb3,
	0x39, 0xae, 0xf0, 0x9c, 0x5f, 0xc8, 0x4f, 0x00, 0x8f, 0x78, 0x61, 0x2d, 0x61, 0x5b, 0x5c, 0x58,
	0x96, 0xb9, 0xac, 0x18, 0x40, 0xca, 0xd4, 0x1f, 0xbc, 0x7c, 0xdf, 0x98, 0x6d, 0x2e, 0xab, 0xc6,
	0x95, 0x65, 0xc5, 0x1e, 0x41, 0xd9, 0x5b, 0x21, 0x9f, 0x98, 0xb3, 0xb2, 0xbf, 0xa8, 0xe0, 0xee,
	0x5f, 0x75, 0x30, 0xc6, 0x7e, 0x70, 0x56, 0xfe, 0xbf, 0xea, 0x80, 0x36, 0x1d, 0xce, 0x5e, 0x0e,
	0x47, 0x3f, 0x0e, 0xcd, 0x1a, 0xdb, 0x06, 0xc3, 0x73, 0x5e, 0x0c, 0x67, 0xce, 0x70, 0xe6, 0xda,
	0x3f, 0x98, 0x75, 0x66, 0x42, 0x67, 0x05, 0x78, 0x63, 0xb3, 0x81, 0x17, 0xbc, 0x37, 0xc3, 0x01,
	0xf1, 0x0a, 0xdb, 0x02, 0x5d, 0x5a, 0xde, 0xd8, 0x6c, 0xa2, 0xfb, 0x81, 0xdd, 0xdf, 0x7f, 0x66,
	0xf7, 0x27, 0xe4, 0xd0, 0x62, 0x37, 0x60, 0x6b, 0x0d, 0xf1, 0xc6, 0x66, 0x9b, 0xdd, 0x04, 0xd3,
	0xb3, 0x87, 0xfb, 0xb3, 0x23, 0xdb, 0xf3, 0xfa, 0x2f, 0x6c, 0x72, 0x54, 0xd9, 0x2d, 0xb8, 0x71,
	0x05, 0xf5, 0xc6, 0xa6, 0xc6, 0x0c, 0x50, 0x25, 0x62, 0xea, 0xf8, 0xbc, 0x92, 0xee, 0x0f, 0x5e,
	0x9a, 0xb0, 0xbb, 0xac, 0x3e, 0x52, 0x2a, 0xc6, 0x00, 0x75, 0xdf, 0x7e, 0xde, 0x3f, 0x9c, 0x4e,
	0xcc, 0x1a, 0xd3, 0xa0, 0x39, 0xb1, 0x5f, 0x4f, 0xcc, 0x3a, 0x9e, 0x9e, 0xf7, 0x07, 0xb6, 0xd9,
	0x60, 0x3a, 0xb4, 0x5e, 0x8d, 0x9c, 0x81, 0x6d, 0x2a, 0x78, 0x74, 0x8e, 0x30, 0x6c, 0x93, 0x78,
	0xe7, 0xd0, 0x36, 0x5b, 0x58, 0xdc, 0xe1, 0x68, 0xd0, 0x9f, 0x38, 0xa3, 0xa1, 0xd9, 0xc6, 0x70,
	0x83, 0xd1, 0xd1, 0x51, 0x7f, 0xb8, 0x6f, 0xaa, 0x0c, 0xa0, 0x3d, 0x98, 0x7a, 0x93, 0xd1, 0x91,
	0xa9, 0xed, 0x3e, 0x06, 0xd5, 0xce, 0xb2, 0x01, 0xae, 0x25, 0x03, 0x54, 0x6f, 0x3a, 0x18, 0xd8,
	0x9e, 0x67, 0xd6, 0xd8, 0x47, 0xd0, 0xf5, 0x6c, 0xf7, 0x95, 0xed, 0xce, 0xa6, 0x43, 0x21, 0xe9,
	0xdf, 0xea, 0xee, 0x57, 0xd0, 0x59, 0x5f, 0xd7, 0x78, 0xa3, 0x64, 0xe9, 0x91, 0x53, 0xcf, 0x76,
	0xcd, 0x3a, 0xbe, 0xe7, 0x85, 0x3b, 0x9a, 0x8e, 0xcd, 0xc6, 0x71, 0x9b, 0xfe, 0x41, 0x7f, 0xf3,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xd1, 0x7c, 0x97, 0x53, 0x0b, 0x00, 0x00,
}
