// Code generated by protoc-gen-go. DO NOT EDIT.
// source: public/proto/protocol.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 消息类型
type MessageType int32

const (
	MessageType_DEFALUT  MessageType = 0
	MessageType_TEXT     MessageType = 1
	MessageType_FACE     MessageType = 2
	MessageType_VOICE    MessageType = 3
	MessageType_IMAGE    MessageType = 4
	MessageType_FILE     MessageType = 5
	MessageType_LOCATION MessageType = 6
	MessageType_CUSTOM   MessageType = 7
)

var MessageType_name = map[int32]string{
	0: "DEFALUT",
	1: "TEXT",
	2: "FACE",
	3: "VOICE",
	4: "IMAGE",
	5: "FILE",
	6: "LOCATION",
	7: "CUSTOM",
}

var MessageType_value = map[string]int32{
	"DEFALUT":  0,
	"TEXT":     1,
	"FACE":     2,
	"VOICE":    3,
	"IMAGE":    4,
	"FILE":     5,
	"LOCATION": 6,
	"CUSTOM":   7,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{0}
}

// 设备登录
type SignIn struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignIn) Reset()         { *m = SignIn{} }
func (m *SignIn) String() string { return proto.CompactTextString(m) }
func (*SignIn) ProtoMessage()    {}
func (*SignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{0}
}

func (m *SignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignIn.Unmarshal(m, b)
}
func (m *SignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignIn.Marshal(b, m, deterministic)
}
func (m *SignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignIn.Merge(m, src)
}
func (m *SignIn) XXX_Size() int {
	return xxx_messageInfo_SignIn.Size(m)
}
func (m *SignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SignIn.DiscardUnknown(m)
}

var xxx_messageInfo_SignIn proto.InternalMessageInfo

func (m *SignIn) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *SignIn) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SignIn) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 设备登录回执
type SignInACK struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrInfo              string   `protobuf:"bytes,2,opt,name=err_info,json=errInfo,proto3" json:"err_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInACK) Reset()         { *m = SignInACK{} }
func (m *SignInACK) String() string { return proto.CompactTextString(m) }
func (*SignInACK) ProtoMessage()    {}
func (*SignInACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{1}
}

func (m *SignInACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInACK.Unmarshal(m, b)
}
func (m *SignInACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInACK.Marshal(b, m, deterministic)
}
func (m *SignInACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInACK.Merge(m, src)
}
func (m *SignInACK) XXX_Size() int {
	return xxx_messageInfo_SignInACK.Size(m)
}
func (m *SignInACK) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInACK.DiscardUnknown(m)
}

var xxx_messageInfo_SignInACK proto.InternalMessageInfo

func (m *SignInACK) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *SignInACK) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

// 同步消息触发
type SyncTrigger struct {
	SyncSequence         int64    `protobuf:"varint,1,opt,name=sync_sequence,json=syncSequence,proto3" json:"sync_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncTrigger) Reset()         { *m = SyncTrigger{} }
func (m *SyncTrigger) String() string { return proto.CompactTextString(m) }
func (*SyncTrigger) ProtoMessage()    {}
func (*SyncTrigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{2}
}

func (m *SyncTrigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncTrigger.Unmarshal(m, b)
}
func (m *SyncTrigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncTrigger.Marshal(b, m, deterministic)
}
func (m *SyncTrigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncTrigger.Merge(m, src)
}
func (m *SyncTrigger) XXX_Size() int {
	return xxx_messageInfo_SyncTrigger.Size(m)
}
func (m *SyncTrigger) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncTrigger.DiscardUnknown(m)
}

var xxx_messageInfo_SyncTrigger proto.InternalMessageInfo

func (m *SyncTrigger) GetSyncSequence() int64 {
	if m != nil {
		return m.SyncSequence
	}
	return 0
}

// 消息发送
type MessageSend struct {
	ReceiverType         int32          `protobuf:"varint,1,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	ReceiverId           int64          `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	WarnUserIds          []int64        `protobuf:"varint,3,rep,packed,name=warn_user_ids,json=warnUserIds,proto3" json:"warn_user_ids,omitempty"`
	MessageBody          []*MessageBody `protobuf:"bytes,4,rep,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	SendSequence         int64          `protobuf:"varint,5,opt,name=send_sequence,json=sendSequence,proto3" json:"send_sequence,omitempty"`
	SendTime             int64          `protobuf:"varint,6,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageSend) Reset()         { *m = MessageSend{} }
func (m *MessageSend) String() string { return proto.CompactTextString(m) }
func (*MessageSend) ProtoMessage()    {}
func (*MessageSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{3}
}

func (m *MessageSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSend.Unmarshal(m, b)
}
func (m *MessageSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSend.Marshal(b, m, deterministic)
}
func (m *MessageSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSend.Merge(m, src)
}
func (m *MessageSend) XXX_Size() int {
	return xxx_messageInfo_MessageSend.Size(m)
}
func (m *MessageSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSend.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSend proto.InternalMessageInfo

func (m *MessageSend) GetReceiverType() int32 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *MessageSend) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *MessageSend) GetWarnUserIds() []int64 {
	if m != nil {
		return m.WarnUserIds
	}
	return nil
}

func (m *MessageSend) GetMessageBody() []*MessageBody {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

func (m *MessageSend) GetSendSequence() int64 {
	if m != nil {
		return m.SendSequence
	}
	return 0
}

func (m *MessageSend) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

// 消息体
type MessageBody struct {
	MessageType          MessageType     `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=pb.MessageType" json:"message_type,omitempty"`
	MessageContent       *MessageContent `protobuf:"bytes,2,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MessageBody) Reset()         { *m = MessageBody{} }
func (m *MessageBody) String() string { return proto.CompactTextString(m) }
func (*MessageBody) ProtoMessage()    {}
func (*MessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{4}
}

func (m *MessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBody.Unmarshal(m, b)
}
func (m *MessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBody.Marshal(b, m, deterministic)
}
func (m *MessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBody.Merge(m, src)
}
func (m *MessageBody) XXX_Size() int {
	return xxx_messageInfo_MessageBody.Size(m)
}
func (m *MessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBody proto.InternalMessageInfo

func (m *MessageBody) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_DEFALUT
}

func (m *MessageBody) GetMessageContent() *MessageContent {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

// 消息内容
type MessageContent struct {
	// Types that are valid to be assigned to Content:
	//	*MessageContent_Text
	//	*MessageContent_Voice
	//	*MessageContent_Face
	//	*MessageContent_Image
	//	*MessageContent_File
	//	*MessageContent_Location
	//	*MessageContent_Custom
	Content              isMessageContent_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MessageContent) Reset()         { *m = MessageContent{} }
func (m *MessageContent) String() string { return proto.CompactTextString(m) }
func (*MessageContent) ProtoMessage()    {}
func (*MessageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{5}
}

func (m *MessageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageContent.Unmarshal(m, b)
}
func (m *MessageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageContent.Marshal(b, m, deterministic)
}
func (m *MessageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageContent.Merge(m, src)
}
func (m *MessageContent) XXX_Size() int {
	return xxx_messageInfo_MessageContent.Size(m)
}
func (m *MessageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageContent.DiscardUnknown(m)
}

var xxx_messageInfo_MessageContent proto.InternalMessageInfo

type isMessageContent_Content interface {
	isMessageContent_Content()
}

type MessageContent_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MessageContent_Voice struct {
	Voice *Voice `protobuf:"bytes,2,opt,name=voice,proto3,oneof"`
}

type MessageContent_Face struct {
	Face *Face `protobuf:"bytes,3,opt,name=face,proto3,oneof"`
}

type MessageContent_Image struct {
	Image *Image `protobuf:"bytes,4,opt,name=image,proto3,oneof"`
}

type MessageContent_File struct {
	File *File `protobuf:"bytes,5,opt,name=file,proto3,oneof"`
}

type MessageContent_Location struct {
	Location *Location `protobuf:"bytes,6,opt,name=location,proto3,oneof"`
}

type MessageContent_Custom struct {
	Custom *Custom `protobuf:"bytes,7,opt,name=custom,proto3,oneof"`
}

func (*MessageContent_Text) isMessageContent_Content() {}

func (*MessageContent_Voice) isMessageContent_Content() {}

func (*MessageContent_Face) isMessageContent_Content() {}

func (*MessageContent_Image) isMessageContent_Content() {}

func (*MessageContent_File) isMessageContent_Content() {}

func (*MessageContent_Location) isMessageContent_Content() {}

func (*MessageContent_Custom) isMessageContent_Content() {}

func (m *MessageContent) GetContent() isMessageContent_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MessageContent) GetText() *Text {
	if x, ok := m.GetContent().(*MessageContent_Text); ok {
		return x.Text
	}
	return nil
}

func (m *MessageContent) GetVoice() *Voice {
	if x, ok := m.GetContent().(*MessageContent_Voice); ok {
		return x.Voice
	}
	return nil
}

func (m *MessageContent) GetFace() *Face {
	if x, ok := m.GetContent().(*MessageContent_Face); ok {
		return x.Face
	}
	return nil
}

func (m *MessageContent) GetImage() *Image {
	if x, ok := m.GetContent().(*MessageContent_Image); ok {
		return x.Image
	}
	return nil
}

func (m *MessageContent) GetFile() *File {
	if x, ok := m.GetContent().(*MessageContent_File); ok {
		return x.File
	}
	return nil
}

func (m *MessageContent) GetLocation() *Location {
	if x, ok := m.GetContent().(*MessageContent_Location); ok {
		return x.Location
	}
	return nil
}

func (m *MessageContent) GetCustom() *Custom {
	if x, ok := m.GetContent().(*MessageContent_Custom); ok {
		return x.Custom
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageContent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageContent_Text)(nil),
		(*MessageContent_Voice)(nil),
		(*MessageContent_Face)(nil),
		(*MessageContent_Image)(nil),
		(*MessageContent_File)(nil),
		(*MessageContent_Location)(nil),
		(*MessageContent_Custom)(nil),
	}
}

type Text struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{6}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Face struct {
	FaceId               int64    `protobuf:"varint,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	FaceUrl              string   `protobuf:"bytes,2,opt,name=face_url,json=faceUrl,proto3" json:"face_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Face) Reset()         { *m = Face{} }
func (m *Face) String() string { return proto.CompactTextString(m) }
func (*Face) ProtoMessage()    {}
func (*Face) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{7}
}

func (m *Face) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Face.Unmarshal(m, b)
}
func (m *Face) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Face.Marshal(b, m, deterministic)
}
func (m *Face) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Face.Merge(m, src)
}
func (m *Face) XXX_Size() int {
	return xxx_messageInfo_Face.Size(m)
}
func (m *Face) XXX_DiscardUnknown() {
	xxx_messageInfo_Face.DiscardUnknown(m)
}

var xxx_messageInfo_Face proto.InternalMessageInfo

func (m *Face) GetFaceId() int64 {
	if m != nil {
		return m.FaceId
	}
	return 0
}

func (m *Face) GetFaceUrl() string {
	if m != nil {
		return m.FaceUrl
	}
	return ""
}

type Voice struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Duration             int32    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voice) Reset()         { *m = Voice{} }
func (m *Voice) String() string { return proto.CompactTextString(m) }
func (*Voice) ProtoMessage()    {}
func (*Voice) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{8}
}

func (m *Voice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voice.Unmarshal(m, b)
}
func (m *Voice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voice.Marshal(b, m, deterministic)
}
func (m *Voice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voice.Merge(m, src)
}
func (m *Voice) XXX_Size() int {
	return xxx_messageInfo_Voice.Size(m)
}
func (m *Voice) XXX_DiscardUnknown() {
	xxx_messageInfo_Voice.DiscardUnknown(m)
}

var xxx_messageInfo_Voice proto.InternalMessageInfo

func (m *Voice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Voice) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Voice) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Voice) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{9}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

type File struct {
	Id                   int64    `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,14,opt,name=size,proto3" json:"size,omitempty"`
	Url                  string   `protobuf:"bytes,15,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{10}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Location struct {
	Desc                 string   `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{11}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Custom struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Custom) Reset()         { *m = Custom{} }
func (m *Custom) String() string { return proto.CompactTextString(m) }
func (*Custom) ProtoMessage()    {}
func (*Custom) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{12}
}

func (m *Custom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Custom.Unmarshal(m, b)
}
func (m *Custom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Custom.Marshal(b, m, deterministic)
}
func (m *Custom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Custom.Merge(m, src)
}
func (m *Custom) XXX_Size() int {
	return xxx_messageInfo_Custom.Size(m)
}
func (m *Custom) XXX_DiscardUnknown() {
	xxx_messageInfo_Custom.DiscardUnknown(m)
}

var xxx_messageInfo_Custom proto.InternalMessageInfo

func (m *Custom) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 消息发送回执
type MessageSendACK struct {
	SendSequence         int64    `protobuf:"varint,1,opt,name=send_sequence,json=sendSequence,proto3" json:"send_sequence,omitempty"`
	ErrCode              int32    `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrInfo              string   `protobuf:"bytes,3,opt,name=err_info,json=errInfo,proto3" json:"err_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageSendACK) Reset()         { *m = MessageSendACK{} }
func (m *MessageSendACK) String() string { return proto.CompactTextString(m) }
func (*MessageSendACK) ProtoMessage()    {}
func (*MessageSendACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{13}
}

func (m *MessageSendACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendACK.Unmarshal(m, b)
}
func (m *MessageSendACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendACK.Marshal(b, m, deterministic)
}
func (m *MessageSendACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendACK.Merge(m, src)
}
func (m *MessageSendACK) XXX_Size() int {
	return xxx_messageInfo_MessageSendACK.Size(m)
}
func (m *MessageSendACK) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendACK.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendACK proto.InternalMessageInfo

func (m *MessageSendACK) GetSendSequence() int64 {
	if m != nil {
		return m.SendSequence
	}
	return 0
}

func (m *MessageSendACK) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *MessageSendACK) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

// 消息投递
type Message struct {
	Type                 int32          `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Messages             []*MessageItem `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{14}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Message) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

// 单条消息投递
type MessageItem struct {
	MessageId            int64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderType           int32    `protobuf:"varint,2,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	SenderId             int64    `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderDeviceId       int64    `protobuf:"varint,4,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	ReceiverType         int32    `protobuf:"varint,5,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	ReceiverId           int64    `protobuf:"varint,6,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Type                 int32    `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	Content              string   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	SyncSequence         int64    `protobuf:"varint,9,opt,name=sync_sequence,json=syncSequence,proto3" json:"sync_sequence,omitempty"`
	SendTime             int64    `protobuf:"varint,10,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageItem) Reset()         { *m = MessageItem{} }
func (m *MessageItem) String() string { return proto.CompactTextString(m) }
func (*MessageItem) ProtoMessage()    {}
func (*MessageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{15}
}

func (m *MessageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageItem.Unmarshal(m, b)
}
func (m *MessageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageItem.Marshal(b, m, deterministic)
}
func (m *MessageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageItem.Merge(m, src)
}
func (m *MessageItem) XXX_Size() int {
	return xxx_messageInfo_MessageItem.Size(m)
}
func (m *MessageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageItem.DiscardUnknown(m)
}

var xxx_messageInfo_MessageItem proto.InternalMessageInfo

func (m *MessageItem) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MessageItem) GetSenderType() int32 {
	if m != nil {
		return m.SenderType
	}
	return 0
}

func (m *MessageItem) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *MessageItem) GetSenderDeviceId() int64 {
	if m != nil {
		return m.SenderDeviceId
	}
	return 0
}

func (m *MessageItem) GetReceiverType() int32 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *MessageItem) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *MessageItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageItem) GetSyncSequence() int64 {
	if m != nil {
		return m.SyncSequence
	}
	return 0
}

func (m *MessageItem) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

// 投递消息回执
type MessageACK struct {
	MessageId            int64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SyncSequence         int64    `protobuf:"varint,2,opt,name=sync_sequence,json=syncSequence,proto3" json:"sync_sequence,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,3,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageACK) Reset()         { *m = MessageACK{} }
func (m *MessageACK) String() string { return proto.CompactTextString(m) }
func (*MessageACK) ProtoMessage()    {}
func (*MessageACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_7508a9393ed6d356, []int{16}
}

func (m *MessageACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageACK.Unmarshal(m, b)
}
func (m *MessageACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageACK.Marshal(b, m, deterministic)
}
func (m *MessageACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageACK.Merge(m, src)
}
func (m *MessageACK) XXX_Size() int {
	return xxx_messageInfo_MessageACK.Size(m)
}
func (m *MessageACK) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageACK.DiscardUnknown(m)
}

var xxx_messageInfo_MessageACK proto.InternalMessageInfo

func (m *MessageACK) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MessageACK) GetSyncSequence() int64 {
	if m != nil {
		return m.SyncSequence
	}
	return 0
}

func (m *MessageACK) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*SignIn)(nil), "pb.SignIn")
	proto.RegisterType((*SignInACK)(nil), "pb.SignInACK")
	proto.RegisterType((*SyncTrigger)(nil), "pb.SyncTrigger")
	proto.RegisterType((*MessageSend)(nil), "pb.MessageSend")
	proto.RegisterType((*MessageBody)(nil), "pb.MessageBody")
	proto.RegisterType((*MessageContent)(nil), "pb.MessageContent")
	proto.RegisterType((*Text)(nil), "pb.Text")
	proto.RegisterType((*Face)(nil), "pb.Face")
	proto.RegisterType((*Voice)(nil), "pb.Voice")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*Custom)(nil), "pb.Custom")
	proto.RegisterType((*MessageSendACK)(nil), "pb.MessageSendACK")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageItem)(nil), "pb.MessageItem")
	proto.RegisterType((*MessageACK)(nil), "pb.MessageACK")
}

func init() { proto.RegisterFile("public/proto/protocol.proto", fileDescriptor_7508a9393ed6d356) }

var fileDescriptor_7508a9393ed6d356 = []byte{
	// 978 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x6e, 0xe2, 0x9f, 0xd8, 0xc7, 0x69, 0x6a, 0x8d, 0x56, 0x60, 0x76, 0x17, 0xe8, 0x1a, 0x2e,
	0xaa, 0x45, 0x2a, 0x52, 0xb8, 0x83, 0xab, 0x6c, 0x36, 0xa5, 0x86, 0x96, 0x22, 0xd7, 0x5d, 0x2d,
	0x57, 0x91, 0x63, 0x4f, 0xd3, 0xd1, 0xfa, 0x27, 0xd8, 0x4e, 0x77, 0x83, 0x10, 0x2f, 0xc1, 0x5b,
	0xf1, 0x2e, 0xbc, 0x03, 0x3a, 0x67, 0xc6, 0x4e, 0x43, 0x76, 0xb5, 0x37, 0xd1, 0x9c, 0x1f, 0x7f,
	0x67, 0xbe, 0x6f, 0x3c, 0x9f, 0x03, 0x4f, 0x56, 0xeb, 0x45, 0x26, 0x92, 0x6f, 0x57, 0x55, 0xd9,
	0x94, 0xf2, 0x37, 0x29, 0xb3, 0x53, 0x5a, 0xb0, 0xfe, 0x6a, 0xe1, 0x47, 0x60, 0x5e, 0x8b, 0x65,
	0x11, 0x14, 0xec, 0x09, 0xd8, 0x29, 0xbf, 0x17, 0x09, 0x9f, 0x8b, 0xd4, 0xeb, 0x1d, 0xf7, 0x4e,
	0xb4, 0xd0, 0x92, 0x89, 0x20, 0x65, 0x9f, 0xc2, 0x60, 0x5d, 0xf3, 0x0a, 0x4b, 0x7d, 0x2a, 0x99,
	0x18, 0x06, 0x29, 0x7b, 0x04, 0x46, 0x53, 0xbe, 0xe1, 0x85, 0xa7, 0x1d, 0xf7, 0x4e, 0xec, 0x50,
	0x06, 0xfe, 0x04, 0x6c, 0x89, 0x3a, 0x99, 0xfe, 0xcc, 0x3e, 0x03, 0x8b, 0x57, 0xd5, 0x3c, 0x29,
	0x53, 0x4e, 0xb8, 0x46, 0x38, 0xe0, 0x55, 0x35, 0x2d, 0x53, 0xde, 0x96, 0x44, 0x71, 0x5b, 0x12,
	0xae, 0x4d, 0xa5, 0xa0, 0xb8, 0x2d, 0xfd, 0x31, 0x38, 0xd7, 0x9b, 0x22, 0x89, 0x2a, 0xb1, 0x5c,
	0xf2, 0x8a, 0x7d, 0x05, 0x87, 0xf5, 0xa6, 0x48, 0xe6, 0x35, 0xff, 0x7d, 0xcd, 0x8b, 0x84, 0xab,
	0x1d, 0x0e, 0x31, 0x79, 0xad, 0x72, 0xfe, 0xbf, 0x3d, 0x70, 0x2e, 0x79, 0x5d, 0xc7, 0x4b, 0x7e,
	0xcd, 0x8b, 0x14, 0x1f, 0xaa, 0x78, 0xc2, 0xc5, 0x3d, 0xaf, 0xe6, 0xcd, 0x66, 0xd5, 0x8e, 0x1f,
	0xb6, 0xc9, 0x68, 0xb3, 0xe2, 0xec, 0x4b, 0x70, 0xba, 0xa6, 0x8e, 0x1e, 0xb4, 0xa9, 0x20, 0x65,
	0x3e, 0x1c, 0xbe, 0x8d, 0xab, 0x62, 0xae, 0x04, 0xa8, 0x3d, 0xed, 0x58, 0x3b, 0xd1, 0x42, 0x07,
	0x93, 0x37, 0xa4, 0x42, 0xcd, 0xc6, 0x30, 0xcc, 0xe5, 0xe0, 0xf9, 0xa2, 0x4c, 0x37, 0x9e, 0x7e,
	0xac, 0x9d, 0x38, 0xe3, 0xa3, 0xd3, 0xd5, 0xe2, 0x54, 0x6d, 0xe8, 0x45, 0x99, 0x6e, 0x42, 0x27,
	0xdf, 0x06, 0x44, 0x89, 0x17, 0xe9, 0x96, 0x92, 0xa1, 0x28, 0xf1, 0x22, 0x6d, 0x29, 0xe1, 0xa9,
	0x50, 0x53, 0x23, 0x72, 0xee, 0x99, 0xf2, 0x54, 0x30, 0x11, 0x89, 0x9c, 0xfb, 0x7f, 0x75, 0x74,
	0x09, 0xf0, 0xc1, 0x26, 0x3a, 0xb6, 0xa3, 0x9d, 0x4d, 0x20, 0xe1, 0x6e, 0x13, 0xc4, 0xfe, 0x07,
	0x38, 0x6a, 0x9f, 0x49, 0xca, 0xa2, 0xe1, 0x45, 0x43, 0x0a, 0x38, 0x63, 0xf6, 0xe0, 0xb1, 0xa9,
	0xac, 0x84, 0xa3, 0x7c, 0x27, 0xf6, 0xff, 0xee, 0xc3, 0x68, 0xb7, 0x85, 0x7d, 0x01, 0x7a, 0xc3,
	0xdf, 0x35, 0x34, 0xdb, 0x19, 0x5b, 0x08, 0x12, 0xf1, 0x77, 0xcd, 0xf9, 0x41, 0x48, 0x79, 0xf6,
	0x0c, 0x8c, 0xfb, 0x52, 0x24, 0x5c, 0x4d, 0xb1, 0xb1, 0xe1, 0x15, 0x26, 0xce, 0x0f, 0x42, 0x59,
	0x41, 0x88, 0xdb, 0x38, 0xe1, 0xf4, 0x46, 0x29, 0x88, 0xb3, 0x98, 0x1a, 0x28, 0x8f, 0x10, 0x22,
	0x8f, 0x97, 0xdc, 0xd3, 0xb7, 0x10, 0x01, 0x26, 0x10, 0x82, 0x2a, 0x04, 0x21, 0x32, 0xa9, 0x68,
	0x0b, 0x21, 0x32, 0x09, 0x21, 0x32, 0xce, 0x9e, 0x83, 0x95, 0x95, 0x49, 0xdc, 0x88, 0xb2, 0x20,
	0x51, 0x9d, 0xf1, 0x10, 0x7b, 0x2e, 0x54, 0xee, 0xfc, 0x20, 0xec, 0xea, 0xec, 0x6b, 0x30, 0x93,
	0x75, 0xdd, 0x94, 0xb9, 0x37, 0xa0, 0x4e, 0xc0, 0xce, 0x29, 0x65, 0xce, 0x0f, 0x42, 0x55, 0x7b,
	0x61, 0xc3, 0x40, 0xe9, 0xe7, 0x3f, 0x06, 0x1d, 0x29, 0x33, 0xf6, 0x40, 0x0a, 0x5b, 0xd2, 0xf7,
	0xbf, 0x07, 0x1d, 0xb9, 0xe0, 0x7d, 0x42, 0x2e, 0xdb, 0xab, 0x66, 0x62, 0x18, 0xa4, 0x78, 0x23,
	0xa8, 0xb0, 0xae, 0xb2, 0xf6, 0x46, 0x60, 0x7c, 0x53, 0x65, 0xfe, 0x6f, 0x60, 0x90, 0x52, 0x6c,
	0x04, 0x7d, 0xf5, 0x9c, 0x1d, 0xf6, 0x45, 0x8a, 0x83, 0x6a, 0xf1, 0x87, 0x94, 0xd4, 0x08, 0x69,
	0xcd, 0x1e, 0x83, 0x95, 0xae, 0x2b, 0xc9, 0x50, 0xa3, 0x7c, 0x17, 0x33, 0x17, 0x34, 0x84, 0xd7,
	0x09, 0x00, 0x97, 0xfe, 0x9f, 0x60, 0x90, 0x82, 0x7b, 0xd0, 0x8f, 0xc0, 0x78, 0x2b, 0xd2, 0xe6,
	0x4e, 0x61, 0xcb, 0x80, 0x7d, 0x02, 0xe6, 0x1d, 0x17, 0xcb, 0xbb, 0x46, 0x41, 0xab, 0x68, 0x1f,
	0x18, 0xdf, 0xf1, 0xe6, 0x6e, 0x9d, 0x2f, 0x8a, 0x58, 0x64, 0xc4, 0xc9, 0xa0, 0xda, 0xb0, 0x4b,
	0x22, 0xb1, 0x5f, 0x41, 0xc7, 0xd3, 0x51, 0xc3, 0x87, 0xa4, 0x87, 0xe2, 0x55, 0xc4, 0x39, 0xf7,
	0x0e, 0xa5, 0x80, 0xb8, 0xee, 0xb8, 0x8e, 0xa8, 0x4b, 0x72, 0x55, 0x63, 0x8f, 0xb6, 0x7c, 0x5e,
	0x83, 0xd5, 0x9e, 0x25, 0x3e, 0x91, 0xf2, 0x3a, 0x69, 0x8f, 0x01, 0xd7, 0xa8, 0x4e, 0x16, 0x37,
	0xa2, 0x59, 0xa7, 0x52, 0xb5, 0x5e, 0xd8, 0xc5, 0xec, 0x29, 0xd8, 0x59, 0x59, 0x2c, 0x65, 0x51,
	0xa3, 0xe2, 0x36, 0xe1, 0x3f, 0x05, 0x53, 0x9e, 0x3d, 0xe1, 0xc6, 0x4d, 0xdc, 0xe1, 0xc6, 0x4d,
	0xec, 0xbf, 0xe9, 0xee, 0x03, 0xfa, 0x0f, 0x9a, 0xdf, 0xde, 0x25, 0xef, 0xbd, 0xe7, 0x92, 0x3f,
	0x74, 0xc8, 0xfe, 0x87, 0x1d, 0x52, 0xdb, 0x75, 0xc8, 0x9f, 0x60, 0xa0, 0x86, 0xd1, 0xab, 0xb6,
	0xf5, 0x37, 0x5a, 0xb3, 0x6f, 0xc0, 0x52, 0xd7, 0xb5, 0xf6, 0xfa, 0x7b, 0x76, 0x14, 0x34, 0x3c,
	0x0f, 0xbb, 0x06, 0xff, 0x9f, 0x7e, 0x67, 0x25, 0x58, 0x61, 0x9f, 0x03, 0xb4, 0xb6, 0xd0, 0xbd,
	0xa2, 0xb6, 0xca, 0x04, 0x29, 0x7a, 0x26, 0x12, 0x68, 0x6d, 0x55, 0xee, 0x19, 0x64, 0x8a, 0x6c,
	0x45, 0xd9, 0x96, 0xb4, 0x54, 0x6d, 0x6b, 0x5b, 0x64, 0xa8, 0x27, 0xe0, 0xaa, 0xe2, 0xf6, 0x83,
	0xa3, 0x53, 0xcf, 0x48, 0xe6, 0x5f, 0xb6, 0x9f, 0x9d, 0x3d, 0x03, 0x37, 0x3e, 0x6e, 0xe0, 0xe6,
	0x9e, 0x81, 0xb7, 0xea, 0x0c, 0x1e, 0xa8, 0xe3, 0x75, 0xf7, 0xd5, 0xb3, 0xa4, 0xac, 0x2a, 0xdc,
	0xff, 0xd2, 0xd8, 0xfb, 0x5f, 0x9a, 0x5d, 0x5b, 0x86, 0xff, 0xd9, 0x72, 0x0d, 0xa0, 0xb4, 0xc4,
	0x37, 0xe0, 0x23, 0x52, 0xee, 0x8d, 0xeb, 0xbf, 0x67, 0xdc, 0x33, 0x68, 0x29, 0xcb, 0x89, 0x52,
	0xd1, 0x96, 0x36, 0x0e, 0x7d, 0x7e, 0xd7, 0x1d, 0x20, 0x89, 0xe2, 0xc0, 0xe0, 0xe5, 0xec, 0x6c,
	0x72, 0x71, 0x13, 0xb9, 0x07, 0xcc, 0x02, 0x3d, 0x9a, 0xbd, 0x8e, 0xdc, 0x1e, 0xae, 0xce, 0x26,
	0xd3, 0x99, 0xdb, 0x67, 0x36, 0x18, 0xaf, 0xae, 0x82, 0xe9, 0xcc, 0xd5, 0x70, 0x19, 0x5c, 0x4e,
	0x7e, 0x9c, 0xb9, 0x3a, 0xd5, 0x83, 0x8b, 0x99, 0x6b, 0xb0, 0x21, 0x58, 0x17, 0x57, 0xd3, 0x49,
	0x14, 0x5c, 0xfd, 0xe2, 0x9a, 0x0c, 0xc0, 0x9c, 0xde, 0x5c, 0x47, 0x57, 0x97, 0xee, 0x60, 0x61,
	0xd2, 0xbf, 0x87, 0xef, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x38, 0x08, 0xd6, 0xc5, 0x5c, 0x08,
	0x00, 0x00,
}
